/**
 * Maps API error codes to short system titles.
 */
const MESSAGES = {
  NETWORK: 'CONNECTION INTERRUPTED',
  TIMEOUT: 'SERVER DID NOT RESPOND',
  TOKEN_EXPIRED: 'SESSION EXPIRED',
  SESSION_EXPIRED: 'TIME IS UP',
  SESSION_COMPLETED: 'CASE ALREADY CLOSED',
  SESSION_NOT_FOUND: 'INVESTIGATION NOT STARTED',
  SESSION_REVOKED: 'SESSION REVOKED',
  STALE_SESSION: 'PLEASE RETRY',
  INVALID_TOKEN: 'IDENTITY TOKEN INVALID',
  NO_TOKEN: 'AUTHENTICATION REQUIRED',
  INVALID_CREDENTIALS: 'IDENTITY VERIFICATION FAILED',
  ACCOUNT_DISABLED: 'CREDENTIAL REVOKED',
  ROLE_FORBIDDEN: 'CLEARANCE INSUFFICIENT',
  EVENT_NOT_STARTED: 'INVESTIGATION NOT STARTED',
  EVENT_PAUSED: 'INVESTIGATION PAUSED',
  EVENT_ENDED: 'INVESTIGATION ENDED',
  EVENT_FULL: 'INVESTIGATION AT CAPACITY',
  FILE_LOCKED: 'FILE LOCKED',
  CHALLENGE_NOT_ACTIVE: 'NOT OPEN YET',
  CHALLENGE_ALREADY_COMPLETED: 'ALREADY CLOSED',
  ATTEMPTS_EXHAUSTED: 'NO ATTEMPTS LEFT',
  FINAL_LOCKED: 'FINAL FILE LOCKED',
  HINT_NOT_FOUND: 'HINT UNAVAILABLE',
  QUERY_REQUIRED: 'RUN A QUERY FIRST',
  QUERY_ATTEMPT_NOT_FOUND: 'QUERY NOT FOUND',
  RATE_LIMITED: 'SLOW DOWN',
  QUERY_RATE_LIMITED: 'QUERY RATE EXCEEDED',
  SUBMIT_RATE_LIMITED: 'TOO MANY SUBMISSIONS',
  TOO_MANY_QUERIES: 'QUERY STILL RUNNING',
  DB_UNAVAILABLE: 'DATABASE UNREACHABLE',
  SQL_ENGINE_OFFLINE: 'SQL ENGINE OFFLINE',
  SQL_ENGINE_RESTART: 'SQL ENGINE RESTARTING',
  SQL_ERROR: 'SQL ERROR',
  SQL_TIMEOUT: 'QUERY TIMED OUT',
  SQL_FORBIDDEN_KEYWORD: 'READ-ONLY DATABASE',
  SQL_READ_ONLY: 'READ-ONLY DATABASE',
  SQL_MULTIPLE_STATEMENTS: 'ONE STATEMENT AT A TIME',
  SQL_SYSTEM_TABLE: 'SYSTEM TABLES BLOCKED',
  SQL_TOO_LONG: 'QUERY TOO LONG',
  SQL_EMPTY: 'EMPTY QUERY',
  VALIDATION_FAILED: 'INVALID INPUT',
  CONTENT_LOCKED: 'CONTENT LOCKED WHILE LIVE',
  EVENT_CONTENT_LOCKED: 'SETTINGS LOCKED WHILE LIVE',
  DATASET_LOCKED: 'DATASET LOCKED WHILE LIVE',
  RESET_CONFIRMATION_REQUIRED: 'CONFIRMATION REQUIRED',
  REQUEST_IN_PROGRESS: 'ALREADY PROCESSING',
};

export function errorTitle(err) {
  return MESSAGES[err?.code] || (err?.status >= 500 ? 'INTERNAL SERVER FAULT' : 'OPERATION FAILED');
}

export function errorMessage(err) {
  if (!err) return 'Unknown fault.';
  if (err.details?.length) return err.details.map((d) => `${d.path ? `${d.path}: ` : ''}${d.message}`).join(' · ');
  return err.message || 'Unknown fault.';
}
